=== yeongjune/site/src/com/base/excel/tableSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
elementFormDefault="qualified" attributeFormDefault="qualified">

	<xs:element name="root">
		<xs:complexType>
			<xs:sequence>
				<xs:choice minOccurs="0">
					<xs:element name="workbook" maxOccurs="unbounded">
						<xs:complexType mixed="true">
							<xs:sequence>
								<xs:element name="sheet">
									<xs:complexType>
										<xs:sequence>
											<xs:element name="export" minOccurs="0" maxOccurs="1">
												<xs:complexType>
													<xs:attribute name="name" type="xs:string" fixed="export" use="required"></xs:attribute>
													<xs:attribute name="class" type="xs:string" use="required"></xs:attribute>
												</xs:complexType>
											</xs:element>
											<xs:element name="import" minOccurs="0" maxOccurs="1">
												<xs:complexType>
													<xs:attribute name="name" type="xs:string" fixed="import" use="required"></xs:attribute>
													<xs:attribute name="class" type="xs:string" use="required"></xs:attribute>
												</xs:complexType>
											</xs:element>
											<xs:element name="table">
												<xs:complexType>
													<xs:sequence>
														<xs:element name="column" minOccurs="0" maxOccurs="unbounded">
															<xs:complexType>
																<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
																<xs:attribute name="column" type="xs:string" use="required"></xs:attribute>
																<xs:attribute name="type" type="xs:string" use="required"></xs:attribute>
																<xs:attribute name="format" type="xs:string"></xs:attribute>
																<xs:attribute name="reg" type="xs:string"></xs:attribute>
																<xs:attribute name="regTip" type="xs:string"></xs:attribute>
																<xs:attribute name="nameSpace" type="xs:string"></xs:attribute>
																<xs:attribute name="valueMethod" type="xs:string"></xs:attribute>
																<xs:attribute name="linkage" type="xs:string"></xs:attribute>
																<xs:attribute name="checkMethod" type="xs:string"></xs:attribute>
																<xs:attribute name="sort" type="xs:int"></xs:attribute>
																<xs:attribute name="unique" type="xs:string"></xs:attribute>
															</xs:complexType>
														</xs:element>
													</xs:sequence>
													<xs:attribute name="name" type="xs:string" fixed="columns" use="required"></xs:attribute>
												</xs:complexType>
											</xs:element>
										</xs:sequence>
										<xs:attribute name="name" type="xs:string" fixed="Sheet1" use="required"></xs:attribute>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
							<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
						</xs:complexType>
					</xs:element>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== yeongjune/site/src/com/base/excel/table.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="tableSchema.xsd">
	<!-- 成绩导入导出 -->
	<workbook name="interviewResult">
		<sheet name="Sheet1">
			<export name="export" class="com.base.excel.impl.ResultExport"></export>
			<import name="import" class="com.base.excel.impl.ResultImport"></import>
			<table name="columns">
				<column name="学校名称" column="graduate" type="String" format="@"></column>			
				<column name="姓名" column="name" type="String" format="@"></column>
				<column name="性别" column="gender" type="String" format="@" nameSpace="genders"></column>
				<column name="联系电话" column="phoneNumber" type="String" format="@"></column>
				<column name="面试批次" column="batch" type="String" format="@"></column>
				<column name="面试时间" column="interviewDate" type="String" format="@"></column>
				<column name="是否参加面试" column="interview" type="String" format="@" nameSpace="yesOrNo"></column>
				<column name="是否录取" column="admit" type="String" format="@" nameSpace="admit"></column>
				<column name="面试成绩" column="interviewScore" type="Double" format="@"></column>
			</table>
		</sheet>
	</workbook>
	<!-- 学生信息汇总导出 -->
	<workbook name="studentInfor">
		<sheet name="Sheet1">
			<export name="export" class="com.base.excel.impl.StudentInforExport"></export>
			<table name="columns">
				<column name="姓名" column="name" type="String" format="@"></column>
				<column name="性别" column="gender" type="String" format="@" nameSpace="genders"></column>
				<column name="证件类型" column="certificateType" type="String" format="@" valueMethod="certificateType"></column>
				<column name="证件号码" column="certificate" type="String" format="@"></column>
				<column name="小学籍号" column="enrollmentNumbers" type="String" format="@"></column>
				<column name="民族" column="nationality" type="String" format="@"></column>
				<column name="籍贯" column="nativePlace" type="String" format="@"></column>
				<column name="户籍所在地" column="domicile" type="String" format="@"></column>
				<column name="家庭地址" column="homeAddress" type="String" format="@"></column>
				<column name="毕业院校" column="graduate" type="String" format="@"></column>
				<column name="出生日期" column="birthday" type="String" format="@"></column>
				<column name="手机号" column="phoneNumber" type="String" format="@"></column>
				<column name="语文成绩" column="chinese" type="String" format="@"></column>
				<column name="数学成绩" column="maths" type="String" format="@"></column>
				<column name="英语成绩" column="english" type="String" format="@"></column>
				<column name="面试成绩" column="interviewScore" type="String" format="@"></column>
				<column name="综合成绩" column="allTotal" type="String" format="@"></column>
				<column name="是否参加面试" column="interview" type="String" format="@"   nameSpace="yesOrNo"></column>
				<column name="是否录取" column="admit" type="String" format="@"   nameSpace="admit"></column>   
				<column name="报名时间" column="createTime" type="String" format="@"></column>
				<column name="面试时间" column="interviewDate" type="String" format="@"></column>
				<column name="联系人1姓名" column="fullName1" type="String" format="@"></column>
				<column name="联系人1关系" column="relationship1" type="String" format="@"></column>
				<column name="联系人1电话" column="telephone1" type="String" format="@"></column>
				<column name="联系人1单位" column="unit1" type="String" format="@"></column>
				<column name="联系人1职位" column="position1" type="String" format="@"></column>
				<column name="联系人2姓名" column="fullName2" type="String" format="@"></column>
				<column name="联系人2关系" column="relationship2" type="String" format="@"></column>
				<column name="联系人2电话" column="telephone2" type="String" format="@"></column>
				<column name="联系人2单位" column="unit2" type="String" format="@"></column>
				<column name="联系人2职位" column="position2" type="String" format="@"></column>
				<column name="五六年级获奖情况和个人特长" column="rewardHobby" type="String" format="@"></column>
			</table>
		</sheet>
	</workbook>
	<!-- 成绩统计导出 -->
	<workbook name="scodeInfor">
		<sheet name="Sheet1">
			<export name="export" class="com.base.excel.impl.ScodeExport"></export>
			<table name="columns">
				<column name="学校名" column="graduate" type="String" format="@"></column>
				<column name="报名人数" column="applyCount" type="String" format="@"></column>
				<column name="面试人数" column="interviewCount" type="String" format="@"></column>
				<column name="平均语文成绩" column="avgOfChinese" type="String" format="@"></column>
				<column name="平均数学成绩" column="avgOfMaths" type="String" format="@"></column>
				<column name="平均英语成绩" column="avgOfEnglish" type="String" format="@"></column>
				<column name="平均面试成绩" column="AvgOfInterview" type="String" format="@"></column> 
				<column name="录取人数" column="admitCount" type="String" format="@"></column>
				<column name="未录取人数" column="notAdmitCount" type="String" format="@"></column>
				<column name="待公布录取" column="watingAdmitCount" type="String" format="@"></column>
			</table>
		</sheet>
	</workbook>
	<!-- 报名统计导出 -->
	<workbook name="applyInfor">
		<sheet name="Sheet1">
			<export name="export" class="com.base.excel.impl.ApplyExport"></export>
			<table name="columns">
				<column name="学校名" column="graduate" type="String" format="@"></column>
				<column name="报名人数" column="applyCount" type="String" format="@"></column>
				<column name="面试人数" column="interviewCount" type="String" format="@"></column>
				<column name="待审核人数" column="watingCheck" type="String" format="@"></column>
				<column name="审核通过人数" column="passCheck" type="String" format="@"></column>
				<column name="审核回退人数" column="backCheck" type="String" format="@"></column>
				<column name="审核不通过人数" column="notPassCheck" type="String" format="@"></column> 
				<column name="录取人数" column="admitCount" type="String" format="@"></column>
				<column name="未录取人数" column="notAdmitCount" type="String" format="@"></column>
				<column name="待公布录取" column="watingAdmitCount" type="String" format="@"></column>
			</table>
		</sheet>
	</workbook>
	
	<!-- 导入/导出面试时间和批次 -->
	<workbook name="interviewDateAndBatch">
		<sheet name="Sheet1">
			<export name="export" class="com.base.excel.impl.InterviewDateAndBatchExport"></export>
			<import name="import" class="com.base.excel.impl.InterviewDateAndBatchImport"></import>
			<table name="columns">
				<column name="学校名称" column="graduate" type="String" format="@"></column>			
				<column name="姓名" column="name" type="String" format="@"></column>
				<column name="性别" column="gender" type="String" format="@" nameSpace="genders"></column>
				<column name="联系电话" column="phoneNumber" type="String" format="@"></column>
				<column name="面试时间(例子:2014-06-28 9:00-12:00)" column="interviewDate" type="String" format="@"></column>
			</table>
		</sheet>
	</workbook>
	<!-- 导入/导出面试时间和批次(民航初中报名) -->
	<workbook name="interviewDateAndBatch1">
		<sheet name="Sheet1">
			<export name="export" class="com.base.excel.impl.InterviewDateAndBatchExport1"></export>
			<import name="import" class="com.base.excel.impl.InterviewDateAndBatchImport1"></import>
			<table name="columns">
				<column name="编号" column="number" type="String" format="@"></column>
				<column name="准考证号" column="testCard" type="String" format="@"></column>
				<column name="姓名" column="name" type="String" format="@"></column>
				<column name="性别" column="gender" type="String" format="@" nameSpace="genders"></column>
				<column name="身份证号" column="IDCard" type="String" format="@"></column>
				<column name="出生日期" column="birthday" type="String" format="@"></column>
				<column name="全国学籍号" column="inSchoolNo" type="String" format="@" ></column>
				<column name="是否广州学籍" column="isGZSchoolNo" type="String" format="@" ></column>
				<column name="广州学籍好" column="inGzSchoolNo" type="String" format="@" ></column>
				<column name="曾任何种职务" column="position" type="String" format="@" ></column>
				<column name="户籍" column="nativePlace" type="String" format="@" ></column>
				<column name="户口所在" column="domicile" type="String" format="@" ></column>
				<column name="是否是农业户口" column="IsPeasant" type="String" format="@" ></column>
				<column name="学科竞赛获奖情况" column="rewardHobby" type="String" format="@" ></column>
				<column name="家庭电话" column="homePhone" type="String" format="@"></column>
				<column name="父亲联系电话" column="fatherPhone" type="String" format="@"></column>
				<column name="父亲身份证号" column="fatherIDCard" type="String" format="@"></column>
				<column name="母亲联系电话" column="matherPhone" type="String" format="@"></column>
				<column name="母亲身份证号" column="motherIDCard" type="String" format="@"></column>
				<column name="现家庭住址" column="homeAddress" type="String" format="@"></column>
				<column name="毕业学校" column="graduate" type="String" format="@"></column>			
				<column name="单位" column="companyName" type="String" format="@"></column>			
				<column name="面试时间(例子:2014-06-28 9:00-12:00)" column="interviewDate" type="String" format="@"></column>
				<column name="是否面试" column="interview" type="String" format="@"></column>
				<column name="面试成绩" column="interviewScore" type="String" format="@"></column>
				<column name="是否录取" column="admit" type="String" format="@"></column>
				<column name="考试教室" column="roomNo" type="String" format="@"></column>
				<column name="家庭主要成员1-关系" column="relationship1" type="String" format="@"></column>
				<column name="家庭主要成员1-姓名" column="fullName1" type="String" format="@"></column>
				<column name="家庭主要成员1-工作单位" column="unit1" type="String" format="@"></column>
				<column name="家庭主要成员1-联系电话" column="telephone1" type="String" format="@"></column>
				<column name="家庭主要成员2-关系" column="relationship2" type="String" format="@"></column>
				<column name="家庭主要成员2-姓名" column="fullName2" type="String" format="@"></column>
				<column name="家庭主要成员2-工作单位" column="unit2" type="String" format="@"></column>
